language: generic
sudo: required
services:
    - docker

# before_install:
#     - docker build -t s0288/telegram-test -f ./tests/Dockerfile.telegram .
#     - ...

# script:
#     - docker run s0288/telegram-test -- --coverage

after_success:
    - docker build -t s0288/telegram:latest .
    - docker build -t s2088/flask:latest .
    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to Docker Hub
    - docker push s0288/telegram
    - docker push s0288/flask