language: generic
sudo: required
services:
    - docker

# before_install:
#     - docker build -t s0288/telegram-test -f ./tests/Dockerfile.telegram .
#     - ...

# script:
#     - docker run s0288/telegram-test -- --coverage

after_success:
    - docker build -t s0288/telegram:latest .
    - docker build -t s2088/flask:latest .
    - docker build -t s0288/rasa:latest .
    - docker build -t s0288/actions:latest .
    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to Docker Hub
    - docker push s0288/telegram
    - docker push s0288/flask
    - docker push s0288/rasa
    - docker push s0288/actions

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: aya
    env: Aya-env-1
    bucket_name: elasticbeanstalk-eu-central-1-447969878826
    bucket_path: aya-bucket
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY