version: '3'

services:
    telegram:
        image: s0288/telegram
        environment:
            - POSTGRES=${POSTGRES}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - RASA_WEBHOOK=${RASA_WEBHOOK}
        networks:
            - aya
    flask:
        image: s0288/flask
        environment:
            - POSTGRES=${POSTGRES}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        networks:
            - aya
        ports:
            - "5000:5000"
    rasa:
        image: rasa/rasa:1.10.3-full
        networks:
            - aya
        ports:
            - "5005:5005"
        volumes:
            - ./rasa:/app
        command: run
    actions:
        image: s0288/actions
        networks:
            - aya
        ports:
            - "5055:5055"
        volumes:
            - ./rasa:/app/rasa

networks:
    aya: