version: '3'

services:
    telegram:
        image: s0288/telegram
        networks:
            - aya
    flask:
        image: s0288/flask
        networks:
            - aya
        ports:
            - "5000:5000"
    rasa:
        image: s0288/rasa
        networks:
            - aya
        ports:
            - "5005:5005"
        volumes:
            - ./rasa:/app
    actions:
        image: s0288/actions
        networks:
            - aya
        ports:
            - "5055:5055"
        volumes:
            - ./rasa:/app/rasa

networks:
    aya: